### PR TITLE
RoutingNode Put Flow.

### PR DESCRIPTION
**Pull request by BSMaidSafe**
[Review on Reviewable](https://reviewable.io/reviews/dirvine/routing/123)

### CODE REVIEW

**Comment by dirvine** [comment]
Reviewed files:
- src/messages/put_data_response.rs @ r1
- src/routing_node.rs @ r1

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dirvine/routing/123)

**Comment by dirvine** [comment]
This is good work, but unfortunately cannot merge as coverage decreased. Can we please look at a test. We will allocate a test task for this.  

---









Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dirvine/routing/123)

**Comment by dirvine** [comment]
deciding to override the coverage decrease as this will stop others in routing node progressing. It loks like good code but we will need to add a test later.

**Comment by BSMaidSafe** [comment]
Thanks David. I'll do the tests when the task goes in.

**Comment by dirvine** [comment]
nice one cheers Brian

**Pull request merged**
